# Generated by Django 4.2.13 on 2024-08-19 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_number', models.CharField(max_length=50, unique=True)),
                ('btn', models.CharField(blank=True, max_length=20)),
                ('voice_channel_count', models.IntegerField(blank=True, null=True)),
                ('contract_details', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('supported_codecs', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('e164_code', models.CharField(blank=True, max_length=10, null=True)),
                ('iso2_code', models.CharField(blank=True, max_length=5)),
                ('iso3_code', models.CharField(blank=True, max_length=5)),
                ('numeric_code', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('subregion', models.CharField(blank=True, max_length=50)),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=3)),
                ('currency_name', models.CharField(blank=True, max_length=50)),
                ('language_code', models.CharField(blank=True, max_length=2)),
                ('language_name', models.CharField(blank=True, max_length=50)),
                ('flag_png_url', models.URLField(blank=True, null=True)),
                ('flag_svg_url', models.URLField(blank=True, null=True)),
                ('flag_alt_description', models.CharField(blank=True, max_length=1024, null=True)),
                ('postal_code_format', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code_regex', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('house_number', models.CharField(max_length=20)),
                ('road', models.CharField(max_length=50)),
                ('road_suffix', models.CharField(blank=True, max_length=25, null=True)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('state_abbreviation', models.CharField(blank=True, max_length=5, null=True)),
                ('postcode', models.CharField(max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location_type', models.CharField(blank=True, max_length=50, null=True)),
                ('verified_location', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.country')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255, unique=True)),
                ('website_url', models.URLField(blank=True, max_length=255)),
                ('support_number', models.CharField(blank=True, max_length=20)),
                ('contract_number', models.CharField(blank=True, max_length=255)),
                ('contract_details', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreetSuffix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SwitchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProviderRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_rep_name', models.CharField(max_length=255)),
                ('account_rep_phone', models.CharField(max_length=20)),
                ('account_rep_email', models.EmailField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumberRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_number', models.CharField(max_length=20)),
                ('end_number', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('circuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telephony.circuitdetail')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.country')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.location')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.serviceprovider')),
                ('usage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.usagetype')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('directory_number', models.CharField(max_length=20, unique=True)),
                ('subscriber_number', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('number_format', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('deactivation_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('circuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telephony.circuitdetail')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.country')),
                ('phone_number_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telephony.phonenumberrange')),
                ('service_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.location')),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telephony.serviceprovider')),
                ('usage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.usagetype')),
            ],
        ),
        migrations.AddField(
            model_name='circuitdetail',
            name='connection_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.connectiontype'),
        ),
        migrations.AddField(
            model_name='circuitdetail',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.location'),
        ),
        migrations.AddField(
            model_name='circuitdetail',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.serviceprovider'),
        ),
        migrations.AddField(
            model_name='circuitdetail',
            name='switch_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telephony.switchtype'),
        ),
        migrations.AddConstraint(
            model_name='phonenumber',
            constraint=models.UniqueConstraint(fields=('directory_number',), name='unique_directory_number'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('house_number', 'road', 'city', 'state_abbreviation', 'country')},
        ),
    ]
