# Generated by Django 5.0.6 on 2024-05-25 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=5)),
                ('iso2_code', models.CharField(blank=True, max_length=2)),
                ('iso3_code', models.CharField(blank=True, max_length=3)),
                ('numeric_code', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('subregion', models.CharField(blank=True, max_length=50)),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=3)),
                ('currency_name', models.CharField(blank=True, max_length=50)),
                ('language_code', models.CharField(blank=True, max_length=2)),
                ('language_name', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255)),
                ('website_url', models.URLField(blank=True, max_length=255)),
                ('support_number', models.CharField(blank=True, max_length=20)),
                ('contract_number', models.CharField(blank=True, max_length=255)),
                ('contract_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SwitchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('house_number', models.IntegerField()),
                ('road', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('state_abbreviation', models.CharField(max_length=5)),
                ('postcode', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('location_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.country')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('directory_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('country_code', models.IntegerField()),
                ('region_code', models.IntegerField()),
                ('subscriber_number', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('number_format', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('deactivation_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('service_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.location')),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telephony.serviceprovider')),
                ('usage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.usagetype')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProviderRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_rep_name', models.CharField(max_length=255)),
                ('account_rep_phone', models.CharField(max_length=20)),
                ('account_rep_email', models.EmailField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='CircuitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_number', models.CharField(max_length=50, unique=True)),
                ('btn', models.CharField(blank=True, max_length=20)),
                ('voice_channel_count', models.IntegerField(blank=True, null=True)),
                ('contract_details', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('supported_codecs', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.connectiontype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.location')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.phonenumber')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.serviceprovider')),
                ('switch_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telephony.switchtype')),
            ],
        ),
    ]
