# Generated by Django 5.0.6 on 2024-05-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telephony", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"]},
        ),
        migrations.RenameField(
            model_name="country",
            old_name="code",
            new_name="e164_code",
        ),
        migrations.AddField(
            model_name="country",
            name="flag_alt_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="flag_png_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="flag_svg_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
