# Generated by Django 4.2.13 on 2024-08-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='google_maps_place_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
