# Generated by Django 4.2.13 on 2024-08-23 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_function',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='telephony.locationfunction'),
        ),
    ]
