# Generated by Django 4.2.13 on 2024-08-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0002_alter_location_location_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='site_dial_code',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
