# Generated by Django 5.0.6 on 2024-05-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "telephony",
            "0002_alter_country_options_rename_code_country_e164_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="e164_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
