# Generated by Django 4.2.13 on 2024-08-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0003_location_site_dial_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='site_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
