# Generated by Django 5.0.6 on 2024-05-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telephony", "0003_alter_country_e164_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="postal_code_format",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="postal_code_regex",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="house_number",
            field=models.CharField(max_length=20),
        ),
    ]
