# Generated by Django 5.0.6 on 2024-05-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0004_country_postal_code_format_country_postal_code_regex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='verified_location',
            field=models.BooleanField(default=False),
        ),
    ]
