# Generated by Django 4.2.13 on 2024-08-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0004_alter_location_site_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='site_dial_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='site_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
