# Generated by Django 4.2.13 on 2024-09-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0005_alter_location_site_dial_code_alter_location_site_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardwareanaloggateway',
            old_name='service_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='hardwaregateway',
            old_name='service_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='hardwarephone',
            old_name='service_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='service_location',
            new_name='location',
        ),
    ]
