# Generated by Django 5.1.1 on 2024-09-08 15:40

import django.db.models.deletion
import telephony.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0006_rename_service_location_hardwareanaloggateway_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitdetail',
            name='connection_type',
            field=models.ForeignKey(default=telephony.models.get_default_connection_type, on_delete=django.db.models.deletion.SET_DEFAULT, to='telephony.connectiontype'),
        ),
        migrations.AlterField(
            model_name='circuitdetail',
            name='location',
            field=models.ForeignKey(default=telephony.models.get_default_location, on_delete=django.db.models.deletion.SET_DEFAULT, to='telephony.location'),
        ),
        migrations.AlterField(
            model_name='circuitdetail',
            name='switch_type',
            field=models.ForeignKey(blank=True, default=telephony.models.get_default_switch_type, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='telephony.switchtype'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.ForeignKey(default=telephony.models.get_default_country, on_delete=django.db.models.deletion.SET_DEFAULT, to='telephony.country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_function',
            field=models.ForeignKey(default=telephony.models.get_default_location_function, on_delete=django.db.models.deletion.SET_DEFAULT, to='telephony.locationfunction'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='circuit',
            field=models.ForeignKey(blank=True, default=telephony.models.get_default_circuit_type, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='telephony.circuitdetail'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='country',
            field=models.ForeignKey(default=telephony.models.get_default_country, on_delete=django.db.models.deletion.SET_DEFAULT, to='telephony.country'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='location',
            field=models.ForeignKey(default=telephony.models.get_default_location, on_delete=django.db.models.deletion.SET_DEFAULT, to='telephony.location'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='service_provider',
            field=models.ForeignKey(blank=True, default=telephony.models.get_default_service_provider, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='telephony.serviceprovider'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='usage_type',
            field=models.ForeignKey(default=telephony.models.get_default_usage_type, on_delete=django.db.models.deletion.SET_DEFAULT, to='telephony.usagetype'),
        ),
        migrations.AlterField(
            model_name='phonenumberrange',
            name='circuit',
            field=models.ForeignKey(blank=True, default=telephony.models.get_default_circuit_type, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='telephony.circuitdetail'),
        ),
        migrations.AlterField(
            model_name='phonenumberrange',
            name='country',
            field=models.ForeignKey(default=telephony.models.get_default_country, on_delete=django.db.models.deletion.SET_DEFAULT, to='telephony.country'),
        ),
        migrations.AlterField(
            model_name='phonenumberrange',
            name='location',
            field=models.ForeignKey(default=telephony.models.get_default_location, on_delete=django.db.models.deletion.SET_DEFAULT, to='telephony.location'),
        ),
        migrations.AlterField(
            model_name='phonenumberrange',
            name='service_provider',
            field=models.ForeignKey(default=telephony.models.get_default_service_provider, on_delete=django.db.models.deletion.SET_DEFAULT, to='telephony.serviceprovider'),
        ),
        migrations.AlterField(
            model_name='phonenumberrange',
            name='usage_type',
            field=models.ForeignKey(default=telephony.models.get_default_usage_type, on_delete=django.db.models.deletion.SET_DEFAULT, to='telephony.usagetype'),
        ),
    ]
