# Generated by Django 5.0.6 on 2024-05-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0006_alter_location_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreetSuffix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='road_suffix',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
