# Generated by Django 5.0.6 on 2024-05-27 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0007_streetsuffix_location_road_suffix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuitdetail',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='circuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telephony.circuitdetail'),
        ),
        migrations.CreateModel(
            name='PhoneNumberRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_number', models.BigIntegerField()),
                ('end_number', models.BigIntegerField(blank=True, null=True)),
                ('circuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telephony.circuitdetail')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.country')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.location')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.serviceprovider')),
                ('usage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephony.usagetype')),
            ],
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='phone_number_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telephony.phonenumberrange'),
        ),
    ]
