# Generated by Django 5.0.6 on 2024-05-27 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0008_remove_circuitdetail_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='region_code',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='country',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='telephony.country'),
            preserve_default=False,
        ),
    ]
