# Generated by Django 5.0.6 on 2024-05-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0009_remove_phonenumber_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='directory_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
