# Generated by Django 5.0.6 on 2024-05-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0010_alter_phonenumber_directory_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberrange',
            name='end_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phonenumberrange',
            name='start_number',
            field=models.CharField(max_length=20),
        ),
    ]
