# Generated by Django 5.1.1 on 2024-10-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0010_circuitdetail_bandwidth'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='trunk_access_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
