# Generated by Django 5.1.1 on 2024-10-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0011_location_trunk_access_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuitdetail',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='hardwareanaloggateway',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='hardwaregateway',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='hardwarephone',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='circuitdetail',
            name='ipv4_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='circuitdetail',
            name='ipv6_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv6'),
        ),
        migrations.AddField(
            model_name='hardwareanaloggateway',
            name='ipv4_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='hardwareanaloggateway',
            name='ipv6_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv6'),
        ),
        migrations.AddField(
            model_name='hardwaregateway',
            name='ipv4_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='hardwaregateway',
            name='ipv6_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv6'),
        ),
        migrations.AddField(
            model_name='hardwarephone',
            name='ipv4_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='hardwarephone',
            name='ipv6_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv6'),
        ),
    ]
