# Generated by Django 5.0.6 on 2024-06-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0011_alter_phonenumberrange_end_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_alt_description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
