# Generated by Django 5.0.6 on 2024-06-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0013_alter_country_e164_code_alter_country_iso2_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_alt_description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
