# Generated by Django 5.0.6 on 2024-06-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0014_alter_country_flag_alt_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitdetail',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phonenumberrange',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceproviderrep',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
