# Generated by Django 5.0.6 on 2024-06-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0016_alter_country_postal_code_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='postal_code_format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='postal_code_regex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
