# Generated by Django 4.2.13 on 2024-07-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0017_alter_country_postal_code_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state_abbreviation',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
