# Generated by Django 4.2.13 on 2024-07-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0018_alter_location_state_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='provider_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
