# Generated by Django 4.2.13 on 2024-07-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0019_alter_serviceprovider_provider_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('house_number', 'road', 'city', 'state', 'country')},
        ),
    ]
