# Generated by Django 4.2.13 on 2024-07-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0020_alter_location_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('house_number', 'road', 'city', 'state_abbreviation', 'country')},
        ),
    ]
